//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InLedger()
        {
            this.InLedgerLocations = new HashSet<InLedgerLocation>();
        }
    
        public int LedgerID { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string Username { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string BatchNumber { get; set; }
        public string SupplierName { get; set; }
        public string SupplierLocation { get; set; }
        public string PoNumber { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InLedgerLocation> InLedgerLocations { get; set; }
    }
}
