//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistic
    {
        public int RequestId { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PickupLocation { get; set; }
        public string DeliveryLocation { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Product Product { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
