//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutLedger()
        {
            this.OutLedgerLocations = new HashSet<OutLedgerLocation>();
        }
    
        public int LedgerID { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DeliveryLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutLedgerLocation> OutLedgerLocations { get; set; }
        public virtual Product Product { get; set; }
    }
}
